name: Deploy Storybook to Github for React Native

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
        matrix:
          node-version: [12.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn
        
      - name: Git
        run:  |
          git config --global credential.helper wincred
          git config --global user.name "chnirt"
          git config --global user.email "trinhchinchin@gmail.com"

      - name: Deploy
        run: yarn deploy