name: Deploy Storybook to Github for React Native

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-18.04

    strategy:
        matrix:
          node-version: [12.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build-storybook-web

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.githubToken }}
          BRANCH: main # The branch the action should deploy to.
          FOLDER: storybook-static # The folder that the build-storybook script generates files.
          CLEAN: true # Automatically remove deleted files from the deploy branch
          TARGET_FOLDER: docs # The folder that we serve our Storybook files from
      
      # - name: Git
      #   run:  |
      #     git config --global credential.helper osxkeychain
      #     git config --global user.name "chnirt"
      #     git config --global user.email "trinhchinchin@gmail.com"

      # - name: Deploy
      #   run: yarn deploy