name: Deploy Storybook to Github for React Native

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-18.04

    strategy:
        matrix:
          node-version: [12.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build-storybook-web

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        run: ls
        with:
          github_token: ${{ secrets.GITHUBTOKEN }}
          publish_dir: ./storybook-static